services:
  postgres:
    image: postgres:16-alpine
    container_name: vof_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: vof_admin
      POSTGRES_PASSWORD: ChristIsLord2026
      POSTGRES_DB: vof_local_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: